// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _102190334_NguyenMinhQuang.Models;

#nullable disable

namespace _102190334_NguyenMinhQuang.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20221017212046_abc")]
    partial class abc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("_102190334_NguyenMinhQuang.Models.HoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EmailKhachHang")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LoaiHoaDonId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaHoaDon")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NgayTao")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LoaiHoaDonId");

                    b.ToTable("HoaDons");
                });

            modelBuilder.Entity("_102190334_NguyenMinhQuang.Models.LoaiHoaDon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("LoaiHoaDons");
                });

            modelBuilder.Entity("_102190334_NguyenMinhQuang.Models.HoaDon", b =>
                {
                    b.HasOne("_102190334_NguyenMinhQuang.Models.LoaiHoaDon", "LoaiHoaDon")
                        .WithMany("HoaDons")
                        .HasForeignKey("LoaiHoaDonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiHoaDon");
                });

            modelBuilder.Entity("_102190334_NguyenMinhQuang.Models.LoaiHoaDon", b =>
                {
                    b.Navigation("HoaDons");
                });
#pragma warning restore 612, 618
        }
    }
}
